export const ADD_TODO = 'ADD_TODO'
export const MORE_CHANCE = 'MORE_CHANCE'
export const ADD_MESSAGE = 'ADD_MESSAGE'
export const DELETE_MESSAGE = 'DELETE_MESSAGE'
export const TOP_MESSAGE = 'TOP_MESSAGE'
