export const FETCH_USER = 'FETCH_USER';
export const FETCH_CLASS = 'FETCH_CLASS';
export const FETCH_STUDENT_LIST = 'FETCH_STUDENT_LIST';
export const FETCH_CLASS_INFO = 'FETCH_CLASS_INFO';
export const FETCH_CHANCE_STUDENT_LIST = 'FETCH_CHANCE_STUDENT_LIST';
export const FETCH_SATISFILED_LIST = 'FETCH_SATISFILED_LIST'
export const FETCH_CHANGE_STATUS = 'FETCH_CHANGE_STATUS'
export const FETCH_DIA_CONTENT = 'FETCH_DIA_CONTENT'


export const FETCH_UNREVIEWED = 'FETCH_UNREVIEWED'
export const FETCH_REVIEWED = 'FETCH_REVIEWED'
export const FETCH_ALL_UNREVIEWED = 'FETCH_ALL_UNREVIEWED'
export const FETCH_ALL_REVIEWED = 'FETCH_ALL_REVIEWED'

export const RETURN_COMMENT = 'RETURN_COMMENT'
export const SUBMIT_COMMENT = 'SUBMIT_COMMENT'
export const CHANCE_SWITCH = 'CHANCE_SWITCH'

export const USER_CHANCE = 'USER_CHANCE'
export const SUBMIT_USER_NAME = 'SUBMIT_USER_NAME'
export const DELETE_ARR_USER = 'DELETE_ARR_USER'
export const SEARCH_NAME = 'SEARCH_NAME'
export const SEARCH_DELETE_USER = 'SEARCH_DELETE_USER'
