export const FETCH_USER = 'FETCH_USER';
export const FETCH_CLASS = 'FETCH_CLASS';
export const FETCH_STUDENT_LIST = 'FETCH_STUDENT_LIST';
export const FETCH_CLASS_INFO = 'FETCH_CLASS_INFO';
export const FETCH_CHANCE_STUDENT_LIST = 'FETCH_CHANCE_STUDENT_LIST';
export const FETCH_SATISFILED_LIST = 'FETCH_SATISFILED_LIST'
export const FETCH_CHANGE_STATUS = 'FETCH_CHANGE_STATUS'
export const FETCH_DIA_CONTENT = 'FETCH_DIA_CONTENT'